name: Deploy to EC2 instance

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the application to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        target: ~/reminders-list/
        source: packages/backend/

    - name: SSH into EC2 instance and start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.13.0/bin"
          cd ~/reminders-list/packages/backend
          npm install
          npm run build
          pm2 start dist/main.js --env production
