name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y nodejs
        sudo npm install -g npm
        cd packages/backend
        sudo npm install

    - name: Run linter and Prettier
      run: |
        cd packages/backend
        npm run lint
        npm run format:check

    - name: Run unit tests
      run: |
        cd packages/backend
        npm run test

    - name: Build application
      run: |
        cd packages/backend
        npm run build
